# copy from k8-expense-volume/backend/manifest.yaml
kind: Service
apiVersion: v1
metadata:
  name: frontend
  namespace: expense
spec:
  type: LoadBalancer
  selector: # labels are used as selectors, it connects to that pod
    app: frontend
    tier: web
    project: expense
  ports:
  - protocol: TCP
    port: 80 # service port
    targetPort: 8080 # target container port